dist: bionic
language: python
python: 3.6

install:
- curl https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get | bash
- pip install chartpress==0.6

script:
- chartpress
- git diff

deploy:
  - provider: script
    script: bash deploy.sh
    on:
      # Only deploy when pushing to master branch or a git tag
      branch: master
      tags: true
