sudo: required

language: python
python:
- '3.6'

install:
- curl https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get | bash
- pip install chartpress==0.3.2
script:
- chartpress
- git diff

deploy:
  - provider: script
    skip_cleanup: true
    script: bash deploy.sh
    on:
      # Only deploy when pushing to master branch or a git tag
      branch: master
      tags: true
