sudo: required

language: python
python:
- '3.6'

install:
- curl https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get | bash
- pip install chartpress==0.3.2
script:
- chartpress --image-prefix=. --tag `date +%y.%m.%d`
- git diff

deploy:
  - provider: script
    skip_cleanup: true
    script: bash deploy.sh 
    on:
      branch: master
      tags: false
  - provider: script
    skip_cleanup: true
    script: bash deploy.sh --tag `date +%y.%m.%d`
    on:
      branch: master
      tags: true
