apiVersion: v1
name: pangeo
version: AUTO_POPULATED_BY_CHARTPRESS_AND_TRAVIS
description: An extention of jupyterhub with extra Pangeo resources
maintainers:
  - name: Jacob Tomlinson (Met Office)
    email: jacob.tomlinson@informaticslab.co.uk
  - name: Joe Hamman (NCAR)
    email: jhamman@ucar.edu
  - name: Guillaume Eynard-Bontemps (CNES)
    email: guillaume.eynard-bontemps@cnes.fr
  - name: Erik Sundell
    email: erik.i.sundell@gmail.com
