# requirements.yaml
dependencies:
- name: jupyterhub
  version: "0.9.0-beta.4.n008.hb20ad22"
  repository: 'https://jupyterhub.github.io/helm-chart/'
  import-values:
    - child: rbac
      parent: rbac
- name: dask-gateway
  version: "0.6.1"
  repository: 'https://dask.org/dask-gateway-helm-repo/'
